name: CI/CD Deploy

on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install pytest

      - name: Run tests
        run: |
          export PYTHONPATH=.
          pytest

      - name: Set up SSH key
        run: |
          echo "$SSH_KEY" > key.pem
          chmod 600 key.pem
        env:
          SSH_KEY: ${{ secrets.SSH_KEY }}

      - name: Deploy to server
        env:
          SERVER_HOST: ${{ secrets.SERVER_HOST }}
          SERVER_USER: ${{ secrets.SERVER_USER }}
        run: |
          ssh -i key.pem -o StrictHostKeyChecking=no $SERVER_USER@$SERVER_HOST <<'ENDSSH'
            pkill -f app.py || true
            rm -rf ~/myapp
            git clone git@github.com:AlikhanIT/repo-root.git ~/myapp
            cd ~/myapp
            python3 -m venv venv
            source venv/bin/activate
            pip install -r requirements.txt
            nohup python3 app.py > out.log 2>&1 &
          ENDSSH

      - name: Send email notification (always)
        if: always()
        run: |
          (echo "Date: $(date -R)"; \
          echo "From: noreply@lokishop.kz"; \
          echo "To: almor.biba@gmail.com"; \
          echo "Subject: =?UTF-8?B?8J+VjSBDSS9DRCBpipeline completed?="; \
          echo "MIME-Version: 1.0"; \
          echo "Content-Type: text/html; charset=UTF-8"; \
          echo "Content-Transfer-Encoding: 8bit"; \
          echo ""; \
          echo "<html><body><h3>✅ CI/CD завершён успешно</h3><p>Flask-приложение прошло тесты и было развернуто.</p></body></html>") > email.txt && \
          curl --url "smtps://lokishop.kz:465" \
            --ssl-reqd \
            --mail-from "noreply@lokishop.kz" \
            --mail-rcpt "almor.biba@gmail.com" \
            --upload-file email.txt \
            --user "noreply@lokishop.kz:TestMan3002!" \
            --insecure --verbose && rm email.txt

          rm email.txt
