name: CI/CD Deploy

on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install pytest

      - name: Run tests
        run: |
          export PYTHONPATH=.
          pytest

      - name: Set up SSH key
        run: |
          echo "$SSH_KEY" > key.pem
          chmod 600 key.pem
        env:
          SSH_KEY: ${{ secrets.SSH_KEY }}

      - name: Deploy to server
        env:
          SERVER_HOST: ${{ secrets.SERVER_HOST }}
          SERVER_USER: ${{ secrets.SERVER_USER }}
        run: |
          ssh -i key.pem -o StrictHostKeyChecking=no $SERVER_USER@$SERVER_HOST <<'ENDSSH'
            pkill -f app.py || true
            rm -rf ~/myapp
            git clone git@github.com:AlikhanIT/repo-root.git ~/myapp
            cd ~/myapp
            python3 -m venv venv
            source venv/bin/activate
            pip install -r requirements.txt
            nohup python3 app.py > out.log 2>&1 &
          ENDSSH

      - name: Send email notification (via curl)
        env:
          SMTP_HOST: ${{ secrets.SMTP_HOST }}
          SMTP_PORT: ${{ secrets.SMTP_PORT }}
          SMTP_USERNAME: ${{ secrets.SMTP_USERNAME }}
          SMTP_PASSWORD: ${{ secrets.SMTP_PASSWORD }}
          EMAIL_TO: ${{ secrets.EMAIL_TO }}
        run: |
          echo "From: $SMTP_USERNAME" > email.txt
          echo "To: $EMAIL_TO" >> email.txt
          echo "Subject: ✅ CI/CD pipeline completed" >> email.txt
          echo "" >> email.txt
          echo "Your Flask app was tested and deployed successfully." >> email.txt

          curl --url "smtps://$SMTP_HOST:$SMTP_PORT" \
            --ssl-reqd \
            --mail-from "$SMTP_USERNAME" \
            --mail-rcpt "$EMAIL_TO" \
            --upload-file email.txt \
            --user "$SMTP_USERNAME:$SMTP_PASSWORD" \
            --insecure
