name: CI/CD Deploy with Docker Compose

on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Set up SSH key
        run: |
          echo "$SSH_KEY" > key.pem
          chmod 600 key.pem
        env:
          SSH_KEY: ${{ secrets.SSH_KEY }}

      - name: Deploy with Docker Compose
        run: |
          ssh -i key.pem -o StrictHostKeyChecking=no ubuntu@194.32.140.92 <<'ENDSSH'
            set -e

            # Установить Docker, если не установлен
            if ! command -v docker &> /dev/null; then
              curl -fsSL https://get.docker.com | sudo sh
              sudo usermod -aG docker $USER
            fi

            # Установить Docker Compose, если не установлен
            if ! command -v docker-compose &> /dev/null && ! command -v docker compose &> /dev/null; then
              sudo curl -L "https://github.com/docker/compose/releases/download/v2.20.2/docker-compose-$(uname -s)-$(uname -m)" -o /usr/local/bin/docker-compose
              sudo chmod +x /usr/local/bin/docker-compose
            fi

            cd ~/repo-root || {
              git clone https://github.com/AlikhanIT/repo-root.git ~/repo-root
              cd ~/repo-root
            }

            git pull
            docker compose down || true
            docker compose up -d --build
          ENDSSH

      - name: Send email notification
        if: always()
        run: |
          (echo "Date: $(date -R)";
          echo "From: noreply@lokishop.kz";
          echo "To: almor.biba@gmail.com";
          echo "Subject: =?UTF-8?B?8J+VjSBDSS9DRCBpipeline completed?=";
          echo "MIME-Version: 1.0";
          echo "Content-Type: text/html; charset=UTF-8";
          echo "Content-Transfer-Encoding: 8bit";
          echo "";
          echo "<html><body><h3>✅ CI/CD завершён успешно</h3><p>Docker Compose перезапущен и проект задеплоен.</p></body></html>") > email.txt && \
          curl --url "smtps://lokishop.kz:465" \
            --ssl-reqd \
            --mail-from "noreply@lokishop.kz" \
            --mail-rcpt "almor.biba@gmail.com" \
            --upload-file email.txt \
            --user "noreply@lokishop.kz:TestMan3002!" \
            --insecure --verbose && rm email.txt || true
