name: CI/CD Deploy

on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install pytest

      - name: Run tests
        run: pytest

      - name: Set up SSH key
        run: |
          echo "$SSH_KEY" > key.pem
          chmod 600 key.pem
        env:
          SSH_KEY: ${{ secrets.SSH_KEY }}

      - name: Deploy to server
        env:
          SERVER_HOST: ${{ secrets.SERVER_HOST }}
          SERVER_USER: ${{ secrets.SERVER_USER }}
        run: |
          ssh -i key.pem -o StrictHostKeyChecking=no $SERVER_USER@$SERVER_HOST <<'EOF'
            pkill -f app.py || true
            rm -rf ~/myapp
            git clone git@github.com:AlikhanIT/repo-root.git ~/myapp
            cd ~/myapp
            python3 -m venv venv
            source venv/bin/activate
            pip install -r requirements.txt
            nohup python3 app.py > out.log 2>&1 &
          EOF

      - name: Send email notification
        env:
          SMTP_HOST: ${{ secrets.SMTP_HOST }}
          SMTP_PORT: ${{ secrets.SMTP_PORT }}
          SMTP_USERNAME: ${{ secrets.SMTP_USERNAME }}
          SMTP_PASSWORD: ${{ secrets.SMTP_PASSWORD }}
          EMAIL_TO: ${{ secrets.EMAIL_TO }}
        run: |
          python3 - <<EOF
import smtplib
import os
from email.message import EmailMessage

msg = EmailMessage()
msg['Subject'] = '✅ CI/CD pipeline completed successfully'
msg['From'] = os.environ['SMTP_USERNAME']
msg['To'] = os.environ['EMAIL_TO']
msg.set_content("Your Flask app was tested and deployed successfully!")

with smtplib.SMTP_SSL(os.environ['SMTP_HOST'], int(os.environ['SMTP_PORT'])) as smtp:
    smtp.login(os.environ['SMTP_USERNAME'], os.environ['SMTP_PASSWORD'])
    smtp.send_message(msg)
EOF
